org apach jackrabbit core config
represent workspac specif secur set
workspac secur config workspacesecurityconfig
configur accesscontrolprovid
bean config beanconfig access control provid config accesscontrolproviderconfig
param accesscontrolproviderconfig
workspac secur config workspacesecurityconfig bean config beanconfig access control provid config accesscontrolproviderconfig
access control provid config accesscontrolproviderconfig access control provid config accesscontrolproviderconfig
return configur accesscontrolprovid
code null code option config entri miss
bean config beanconfig access control provid config getaccesscontrolproviderconfig
access control provid config accesscontrolproviderconfig
